### ISSUE TITLE
Improve ability to make animations

### ISSUE THREAD

**Issue by rjleveque** [clawpack/visclaw#116]
PR #100 and the comments on #114 contain some ideas that should be pursued.

**Comment by ketch** [comment]
Since there hasn't been more demand for this in 4+ years, I'm going to close it.  If I need a more involved animation, I usually just write a custom script.

**Comment by mjberger** [comment]
Not sure what this applies to, but one request I have is to add pngs to a previous
animation without remaking everything.  This is important e.g. when you’ve restarted
a run because it didn’t go far enough.  Plotting can take forever for  highly resolved runs, so
it would be good to have a way to reuse the existing ones, and add to the animations.

**Comment by mandli** [comment]
@mjberger this capability is requested in #189.
