### ISSUE TITLE
Visclaw depends on AMRClaw but shouldn't

### ISSUE THREAD

**Issue by ketch** [clawpack/visclaw#54]
For example, in src/python/visclaw/Iplotclaw.py, there is a line

```
import clawpack.amrclaw.data as amrclaw
```

It seems to me that VisClaw should not have AMRClaw as a dependency.

**Comment by ketch** [comment]
Fixing this would require moving the implementation of gauges from AMRClaw to VisClaw, which would make sense anyway.

**Comment by mandli** [comment]
The issue here is that the `gauges.data` file is being read in to see what gauges are available and what their IDs are.  We could reimplement the same functionality in VisClaw but given that AMRClaw and GeoClaw are the only two packages that uses an input format like that I am not sure this entirely makes sense.

**Comment by ketch** [comment]
Maybe move the AMRClaw import inside the function(s) that use it?  I know this is not officially recommended practice but I feel it makes much more sense in this kind of situation.

**Comment by mandli** [comment]
Both instances I believe are inside functions and try/except blocks.

**Comment by ketch** [comment]
You're right.  I think it's okay to close this, then.
